# fly.toml app configuration file generated for akr-bot on 2024-10-28T01:05:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'akr-bot'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
